"""empty message

Revision ID: 79cb920d4dc1
Revises: ac9d580404a3
Create Date: 2024-05-25 20:50:36.142348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '79cb920d4dc1'
down_revision: Union[str, None] = 'ac9d580404a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ecdict', sa.Column('frq', sa.FLOAT(), nullable=True))
    op.alter_column('ecdict', 'collins',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=500),
               type_=sa.FLOAT(),
               existing_nullable=True)
    op.alter_column('ecdict', 'oxford',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=500),
               type_=sa.FLOAT(),
               existing_nullable=True)
    op.alter_column('ecdict', 'bnc',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=500),
               type_=sa.FLOAT(),
               existing_nullable=True)
    op.alter_column('ecdict', 'audio',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=500),
               type_=sa.FLOAT(),
               existing_nullable=True)
    op.create_index(op.f('ix_ecdict_frq'), 'ecdict', ['frq'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ecdict_frq'), table_name='ecdict')
    op.alter_column('ecdict', 'audio',
               existing_type=sa.FLOAT(),
               type_=mysql.VARCHAR(collation='utf8mb4_general_ci', length=500),
               existing_nullable=True)
    op.alter_column('ecdict', 'bnc',
               existing_type=sa.FLOAT(),
               type_=mysql.VARCHAR(collation='utf8mb4_general_ci', length=500),
               existing_nullable=True)
    op.alter_column('ecdict', 'oxford',
               existing_type=sa.FLOAT(),
               type_=mysql.VARCHAR(collation='utf8mb4_general_ci', length=500),
               existing_nullable=True)
    op.alter_column('ecdict', 'collins',
               existing_type=sa.FLOAT(),
               type_=mysql.VARCHAR(collation='utf8mb4_general_ci', length=500),
               existing_nullable=True)
    op.drop_column('ecdict', 'frq')
    # ### end Alembic commands ###
