"""empty message

Revision ID: ac9d580404a3
Revises: f79d4f551169
Create Date: 2024-05-25 20:35:10.288607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac9d580404a3'
down_revision: Union[str, None] = 'f79d4f551169'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ecdict',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.VARCHAR(length=500), nullable=True),
    sa.Column('phonetic', sa.VARCHAR(length=500), nullable=True),
    sa.Column('definition', sa.TEXT(), nullable=True),
    sa.Column('translation', sa.TEXT(), nullable=True),
    sa.Column('pos', sa.VARCHAR(length=500), nullable=True),
    sa.Column('collins', sa.VARCHAR(length=500), nullable=True),
    sa.Column('oxford', sa.VARCHAR(length=500), nullable=True),
    sa.Column('tag', sa.VARCHAR(length=500), nullable=True),
    sa.Column('bnc', sa.VARCHAR(length=500), nullable=True),
    sa.Column('exchange', sa.VARCHAR(length=500), nullable=True),
    sa.Column('detail', sa.VARCHAR(length=500), nullable=True),
    sa.Column('audio', sa.VARCHAR(length=500), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NULL ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ecdict_audio'), 'ecdict', ['audio'], unique=False)
    op.create_index(op.f('ix_ecdict_bnc'), 'ecdict', ['bnc'], unique=False)
    op.create_index(op.f('ix_ecdict_collins'), 'ecdict', ['collins'], unique=False)
    op.create_index(op.f('ix_ecdict_detail'), 'ecdict', ['detail'], unique=False)
    op.create_index(op.f('ix_ecdict_exchange'), 'ecdict', ['exchange'], unique=False)
    op.create_index(op.f('ix_ecdict_id'), 'ecdict', ['id'], unique=False)
    op.create_index(op.f('ix_ecdict_oxford'), 'ecdict', ['oxford'], unique=False)
    op.create_index(op.f('ix_ecdict_phonetic'), 'ecdict', ['phonetic'], unique=False)
    op.create_index(op.f('ix_ecdict_pos'), 'ecdict', ['pos'], unique=False)
    op.create_index(op.f('ix_ecdict_tag'), 'ecdict', ['tag'], unique=False)
    op.create_index(op.f('ix_ecdict_word'), 'ecdict', ['word'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ecdict_word'), table_name='ecdict')
    op.drop_index(op.f('ix_ecdict_tag'), table_name='ecdict')
    op.drop_index(op.f('ix_ecdict_pos'), table_name='ecdict')
    op.drop_index(op.f('ix_ecdict_phonetic'), table_name='ecdict')
    op.drop_index(op.f('ix_ecdict_oxford'), table_name='ecdict')
    op.drop_index(op.f('ix_ecdict_id'), table_name='ecdict')
    op.drop_index(op.f('ix_ecdict_exchange'), table_name='ecdict')
    op.drop_index(op.f('ix_ecdict_detail'), table_name='ecdict')
    op.drop_index(op.f('ix_ecdict_collins'), table_name='ecdict')
    op.drop_index(op.f('ix_ecdict_bnc'), table_name='ecdict')
    op.drop_index(op.f('ix_ecdict_audio'), table_name='ecdict')
    op.drop_table('ecdict')
    # ### end Alembic commands ###
